postgresql: &postgresql
  adapter: postgresql
  username: <%= ENV['CONTRACTOR_DB_USERNAME_POSTGRES'] %>
  password: <%= ENV['CONTRACTOR_DB_PASSWORD_POSTGRES'] %>
  min_messages: ERROR

defaults: &defaults
  pool: 16
  timeout: 3000
  host: localhost
  <<: *postgresql

development:
  database: contractor_development
  <<: *defaults

test:
  database: contractor_test
  <<: *defaults

production:
  database: contractor_production
  <<: *defaults
